version: "3.8"

services:
    django:
        build: .
        container_name: django
        command: bash -c "python manage.py makemigrations && python manage.py migrate  &&  python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - pgdb
            - redis
    celery:
        build: .
        command: celery -A support worker -l INFO
        volumes:
            - .:/usr/src/
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - django
            - redis
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=Support
            - POSTGRES_USER=django_auth
            - POSTGRES_PASSWORD=asdfgh
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"

volumes:
    pgdata: